export const BasePath  = "/"
export const ForgotpasswordPath  = "/forgotpassword"
export const RegisterPath  = "/register"
export const ProfilePath  = "/profile"
export const JobvaccancyPath  = "/jobvaccancy"
export const JobdetailsPath  = "/jobdetails"
export const WalletPath  = "/wallet"
export const ScoreHistoryPath  = "/scorehistory"